# Generated by Django 4.0 on 2022-01-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0002_alter_post_options_post_title_tag_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='post_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255, verbose_name='Тема поста'),
        ),
    ]
