# Generated by Django 4.0 on 2022-01-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click link', max_length=255),
        ),
    ]
